name: Sincronizar Development con Main

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge y Push a Development
        run: |
          git checkout development
          git pull origin development
          git merge origin/main -m "Sincronizando cambios de main a development"
          git push origin development
