// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopMGR.Contexto;

#nullable disable

namespace ShopMGR.Contexto.Migrations
{
    [DbContext(typeof(ShopMGRDbContexto))]
    [Migration("20260801040859_AgregaPasskey.UserHandle")]
    partial class AgregaPasskeyUserHandle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.ConfiguracionGlobal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("MapsID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Piso")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("int");

                    b.Property<string>("RutaRelativa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdTrabajo");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.HorasYDescripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<float>("Horas")
                        .HasColumnType("real");

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdTrabajo");

                    b.ToTable("HorasYDescripcion");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdPresupuesto");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.MovimientoBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrabajo")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTrabajo");

                    b.ToTable("MovimientoBalance");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Passkey", b =>
                {
                    b.Property<byte[]>("IdCredencial")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("Attestation")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("ClavePublica")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<long>("ContadorLogin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoUso")
                        .HasColumnType("date");

                    b.Property<byte[]>("UserHandle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.HasKey("IdCredencial");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Passkeys");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.PasskeyChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChallengeBase64")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("OpcionesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaExpiracion")
                        .HasDatabaseName("PasskeyChallenges_FechaExpiracion");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ChallengeBase64", "FechaExpiracion")
                        .HasDatabaseName("PasskeyChallenges_ChallengeNoExpirado");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoInsumos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoLabor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoMateriales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaAceptado")
                        .HasColumnType("date");

                    b.Property<double>("HorasEstimadas")
                        .HasColumnType("float");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("date");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdUsuario");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.TelefonoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.ToTable("TelefonoCliente");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<double?>("HorasEstimadas")
                        .HasColumnType("float");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPresupuesto")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TotalLabor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPresupuesto")
                        .IsUnique()
                        .HasFilter("[IdPresupuesto] IS NOT NULL");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Direccion", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Cliente", "Cliente")
                        .WithMany("Direccion")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Foto", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Trabajo", "Trabajo")
                        .WithMany("Fotos")
                        .HasForeignKey("IdTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.HorasYDescripcion", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Trabajo", "Trabajo")
                        .WithMany("HorasDeTrabajo")
                        .HasForeignKey("IdTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Material", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Presupuesto", "Presupuesto")
                        .WithMany("Materiales")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.MovimientoBalance", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Cliente", "Cliente")
                        .WithMany("MovimientosBalance")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopMGR.Dominio.Modelo.Trabajo", "Trabajo")
                        .WithMany()
                        .HasForeignKey("IdTrabajo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Passkey", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Usuario", "Usuario")
                        .WithMany("PassKeys")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.PasskeyChallenge", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Presupuesto", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Cliente", "Cliente")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.RefreshToken", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.TelefonoCliente", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Cliente", "Cliente")
                        .WithMany("Telefono")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Trabajo", b =>
                {
                    b.HasOne("ShopMGR.Dominio.Modelo.Cliente", "Cliente")
                        .WithMany("Trabajos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopMGR.Dominio.Modelo.Presupuesto", "Presupuesto")
                        .WithOne("Trabajo")
                        .HasForeignKey("ShopMGR.Dominio.Modelo.Trabajo", "IdPresupuesto");

                    b.Navigation("Cliente");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Cliente", b =>
                {
                    b.Navigation("Direccion");

                    b.Navigation("MovimientosBalance");

                    b.Navigation("Presupuestos");

                    b.Navigation("Telefono");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Presupuesto", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Trabajo", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("HorasDeTrabajo");
                });

            modelBuilder.Entity("ShopMGR.Dominio.Modelo.Usuario", b =>
                {
                    b.Navigation("PassKeys");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
